/**
 * Données de démonstration utilisées quand l'API WordPress n'est pas disponible.
 * En production, toutes les données viennent de WordPress.
 */
import type { Project, Fragment, ResearchQuestion, Text, SiteSettings } from "./api";

/**
 * Tableau de recherche du site.
 *
 * La Monade n'est volontairement pas une ligne de ce tableau : elle est
 * l'architecture relationnelle qui relie tous les territoires, projets,
 * textes et fragments du site.
 */
export const FALLBACK_RESEARCH: ResearchQuestion[] = [
  {
    id: "q1",
    wp_id: 0,
    title: "Corps et métamorphoses",
    question: "Comment le corps devient-il un lieu d'écriture, de mémoire et de transformation ?",
    description: "Le corps comme langage, archive, matière vulnérable et puissance de métamorphose.",
    genealogies: ["Kathy Acker", "Pier Paolo Pasolini", "Jean Cocteau"],
    contemporaryArtists: ["Kiki Smith", "Wangechi Mutu", "Pauline Curnier Jardin", "Josèfa Ntjam"],
    forms: ["texte", "photographie", "film", "performance", "installation"],
    projectIds: ["trois-doigts", "fragments-joaillerie"],
    fragmentCount: 11,
    lastUpdated: "15 août 2026",
  },
  {
    id: "q2",
    wp_id: 0,
    title: "Surréalisme politique",
    question: "Comment le rêve, l'absurde et le grotesque peuvent-ils révéler les rapports de pouvoir ?",
    description: "L'imaginaire n'est pas une fuite hors du réel, mais une manière de le fissurer.",
    genealogies: ["surréalisme", "situationnisme", "figuration narrative"],
    contemporaryArtists: ["Pauline Curnier Jardin", "Laure Prouvost", "Meriem Bennani", "Monster Chetwynd"],
    forms: ["collage", "détournement", "animation", "cinéma", "récit"],
    projectIds: ["trois-doigts", "futur-animiste", "direction-artistique"],
    fragmentCount: 8,
    lastUpdated: "15 août 2026",
  },
  {
    id: "q3",
    wp_id: 0,
    title: "Images et pouvoir",
    question: "Qui construit, classe, légitime ou rend invisibles les images ?",
    description: "Une enquête sur les conventions du regard, la circulation des images et leur valeur sociale.",
    genealogies: ["Pierre Bourdieu", "Ernst Gombrich", "situationnisme"],
    contemporaryArtists: ["Hito Steyerl", "Kader Attia", "Kapwani Kiwanga"],
    forms: ["enquête", "archive", "montage", "cartographie", "édition"],
    projectIds: ["futur-animiste", "direction-artistique"],
    fragmentCount: 9,
    lastUpdated: "15 août 2026",
  },
  {
    id: "q4",
    wp_id: 0,
    title: "Matière et perception",
    question: "Comment la lumière, le son, la couleur et la matière transforment-ils notre perception ?",
    description: "La couleur possède une vitesse ; la matière, une capacité d'apparition et de réponse.",
    genealogies: ["synesthésie", "vitesse des couleurs", "art cinétique"],
    contemporaryArtists: ["Pipilotti Rist", "Liliane Lijn", "Kiki Smith"],
    forms: ["son", "lumière", "photographie", "vidéo", "installation interactive"],
    projectIds: ["oeil-matiere", "la-monade"],
    fragmentCount: 7,
    lastUpdated: "15 août 2026",
  },
  {
    id: "q5",
    wp_id: 0,
    title: "Systèmes et formes",
    question: "Comment une règle simple peut-elle produire une forme vivante et évolutive ?",
    description: "Des systèmes visuels construits par la géométrie, le rythme, la répétition et la relation.",
    genealogies: ["art concret", "Theo van Doesburg", "Max Bill"],
    contemporaryArtists: ["Tauba Auerbach", "Ryoji Ikeda", "Liliane Lijn"],
    forms: ["design graphique", "typographie", "animation", "architecture numérique"],
    projectIds: ["la-monade", "oeil-matiere", "direction-artistique"],
    fragmentCount: 5,
    lastUpdated: "15 août 2026",
  },
  {
    id: "q6",
    wp_id: 0,
    title: "Cultures modestes",
    question: "Que racontent les objets et les images laissés aux périphéries du grand art ?",
    description: "Déplacer le regard entre cultures savantes, populaires, artisanales et numériques.",
    genealogies: ["art modeste", "Hervé Di Rosa", "Bernard Belluc"],
    contemporaryArtists: ["Pauline Curnier Jardin", "Monster Chetwynd"],
    forms: ["collection", "assemblage", "photographie", "objet", "contre-archive"],
    projectIds: ["fragments-joaillerie", "futur-animiste", "direction-artistique"],
    fragmentCount: 6,
    lastUpdated: "15 août 2026",
  },
];

export const FALLBACK_PROJECTS: Project[] = [
  {
    id: "trois-doigts", wp_id: 0, title: "À trois doigts", category: "anim.", status: "expérimentation",
    year: "2024",
    question: "Ce qu'un corps raconte quand le langage ordinaire ne lui suffit plus.",
    manifeste: "Un film d'animation construit à partir de gestes qui n'existent pas dans les dictionnaires.",
    description: "Court métrage d'animation. Une main à trois doigts invente sa propre grammaire. Pas de dialogue — seulement ce que le geste dit seul.",
    lastUpdated: "12 jan. 2025",
    themes: ["corps", "surréalisme"],
    tags: ["Animation", "Corps", "Narration"],
    image: "https://images.unsplash.com/photo-1585571290034-3f59a2568563?w=1400&h=900&fit=crop&auto=format",
    constellation: { x: 240, y: 180, r: 18 },
    fragmentCount: 14,
    journal: [
      { date: "10 jan. 2025", title: "Le rig invente des gestes", content: "En animant, la main à trois doigts a trouvé des mouvements que je n'avais pas prévus. Je suis en train d'apprendre de mes propres personnages.", type: "découverte" },
      { date: "5 jan. 2025", title: "Problème : la prise d'objet", content: "Comment la main attrape-t-elle un verre sans le quatrième doigt ? Ce n'est pas un problème technique — c'est une question de chorégraphie.", type: "difficulté" },
    ],
    maintenant: { cherche: "La juste distance entre documentaire et fiction. Ne pas expliquer.", avancee: "Le rig fonctionne. Les mouvements inattendus sont les meilleurs.", bloque: "La séquence de la tasse — trop anecdotique pour l'instant.", prochaine: "Animer la séquence d'ouverture sans texte.", question: "Peut-on montrer ce qui manque sans le désigner ?" },
    references: [
      { title: "Rapture", author: "Kiki Smith", year: "2001" },
      { title: "Blood and Guts in High School", author: "Kathy Acker", year: "1984" },
      { title: "Wangechi Mutu — œuvre", author: "Wangechi Mutu", year: "1996–" },
      { title: "Pauline Curnier Jardin — œuvre", author: "Pauline Curnier Jardin", year: "2006–" },
    ],
  },
  {
    id: "oeil-matiere", wp_id: 0, title: "L'Œil de la matière", category: "install.", status: "production",
    year: "2023",
    question: "À partir de quel moment une matière cesse-t-elle d'être passive ?",
    manifeste: "Ni sculpture ni vidéo. Un organisme. La résine qui réagit à la lumière comme une peau.",
    description: "Installation : résine translucide, fibre optique, capteurs de présence. Projet fondateur de La Monade — le dispositif perçoit le spectateur avant que le spectateur ne le perçoive.",
    lastUpdated: "8 jan. 2025",
    themes: ["matière", "systèmes"],
    tags: ["Installation", "Matière", "Système"],
    image: "https://images.unsplash.com/photo-1588203379102-1a06c7d2ba1f?w=1400&h=900&fit=crop&auto=format",
    constellation: { x: 460, y: 140, r: 20 },
    fragmentCount: 21,
    journal: [
      { date: "8 jan. 2025", title: "Test résine + fibre optique", content: "La résine translucide avec des fibres optiques réagit à la chaleur corporelle. Elle n'est plus inerte. Elle attend.", type: "expérimentation" },
    ],
    maintenant: { cherche: "Le point exact où le dispositif technique disparaît et laisse place à l'expérience.", avancee: "La structure et les premières réponses des capteurs sont en cours d'expérimentation.", bloque: null, prochaine: "Documenter une première version du dispositif et ses réactions à la présence.", question: "Comment concevoir quelque chose qui a l'air vivant sans l'imiter ?" },
    references: [
      { title: "Pipilotti Rist — œuvre", author: "Pipilotti Rist", year: "1986–" },
      { title: "Liliane Lijn — œuvre", author: "Liliane Lijn", year: "1960–" },
      { title: "Constellation", author: "Kiki Smith", year: "1996" },
      { title: "Aquarelles dans l'eau", author: "Sarkis", year: "2005–" },
    ],
  },
  {
    id: "la-monade", wp_id: 0, title: "La Monade", category: "rech.", status: "recherche",
    year: "2022–",
    question: "Comment des fragments autonomes peuvent-ils rester reliés par une mémoire commune ?",
    manifeste: "La monade comme programme : être radicalement fermé sur soi et résonner avec tout le reste.",
    description: "Architecture centrale du studio et projet en soi, La Monade relie six territoires de recherche, des projets, des textes et des fragments autonomes. Elle ne constitue pas une catégorie supplémentaire : elle rend leurs connexions visibles.",
    lastUpdated: "15 août 2026",
    themes: ["systèmes", "images"],
    tags: ["Recherche", "Installation", "Écriture"],
    image: "https://images.unsplash.com/photo-1617538716228-213f468a2c6c?w=1400&h=900&fit=crop&auto=format",
    constellation: { x: 370, y: 280, r: 22 },
    fragmentCount: 37,
    journal: [
      { date: "15 déc. 2024", title: "La fermeture comme posture", content: "La monade n'a pas de fenêtre — et pourtant elle reflète l'univers. C'est une posture de travail, pas seulement une métaphore.", type: "hypothèse" },
    ],
    maintenant: { cherche: "La forme plastique qui incarne la tension entre fermeture et résonance — pas une illustration.", avancee: "L'architecture relationnelle et les six territoires de recherche sont définis.", bloque: "Le passage de la théorie à la matière. Comment rendre cette relation physiquement perceptible ?", prochaine: "Cartographier les projets, textes et fragments associés à chaque territoire.", question: "Qu'est-ce qui distingue une forme fermée d'une forme morte ?" },
    references: [
      { title: "Monadologie", author: "Gottfried Leibniz", year: "1714" },
      { title: "Utopia Utopia", author: "Thomas Hirschhorn", year: "2005" },
      { title: "Pensée en archipel", author: "Édouard Glissant", year: "1990" },
      { title: "Constellation", author: "Kiki Smith", year: "1996" },
    ],
  },
  {
    id: "futur-animiste", wp_id: 0, title: "Ce que les images font", category: "rech.", status: "documentation",
    year: "2023–",
    question: "Qui construit, classe, légitime ou rend invisibles les images ?",
    manifeste: "Les images circulent, s'accumulent, se dégradent, réapparaissent. Elles ont une vie propre — et cette vie est politique.",
    description: "Recherche sur la circulation des images numériques : leur survie, leur déformation, ce qu'elles font au monde quand elles ne sont plus sous contrôle.",
    lastUpdated: "15 août 2026",
    themes: ["images", "surréalisme"],
    tags: ["Recherche", "Image", "Archives"],
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=1400&h=900&fit=crop&auto=format",
    constellation: { x: 560, y: 310, r: 16 },
    fragmentCount: 18,
    journal: [
      { date: "Nov. 2024", title: "L'image pauvre comme méthode", content: "Steyerl : l'image pauvre n'est pas une image dégradée. C'est une image qui a voyagé.", type: "hypothèse" },
    ],
    maintenant: { cherche: "Des cas concrets où des images ont changé de sens en circulant.", avancee: "Un premier corpus d'images et de situations de circulation est en cours de classement.", bloque: null, prochaine: "Relier chaque image à son contexte, ses transformations et ses usages successifs.", question: "Une image peut-elle mentir sans intention ?" },
    references: [
      { title: "In Defense of the Poor Image", author: "Hito Steyerl", year: "2009" },
      { title: "Art and Illusion", author: "Ernst Gombrich", year: "1960" },
      { title: "Un art moyen", author: "Pierre Bourdieu et Luc Boltanski", year: "1965" },
      { title: "Earthwork", author: "Kapwani Kiwanga", year: "2018" },
      { title: "Meriem Bennani — œuvre", author: "Meriem Bennani", year: "2010–" },
    ],
  },
  {
    id: "fragments-joaillerie", wp_id: 0, title: "Fragments — Joaillerie", category: "joail.", status: "production",
    year: "2021–",
    question: "Que racontent les objets et les images laissés aux périphéries du grand art ?",
    manifeste: "Ce n'est pas de la joaillerie. C'est une pratique de la réparation — chaque pièce porte la trace de ce qu'elle a traversé.",
    description: "Atelier de création de pièces portées. Les techniques de soudure et de jonction comme langage formel. La marque du travail reste visible. La réparation, pas la restauration.",
    lastUpdated: "3 jan. 2025",
    themes: ["corps", "cultures"],
    tags: ["Joaillerie", "Matière", "Corps"],
    image: "https://images.unsplash.com/photo-1624588057318-5f1b2eb81012?w=1400&h=900&fit=crop&auto=format",
    constellation: { x: 200, y: 340, r: 17 },
    fragmentCount: 29,
    journal: [
      { date: "3 jan. 2025", title: "Série Soudures : décision formelle", content: "Je vais laisser les soudures visibles. La jonction n'est pas un défaut — c'est le sujet.", type: "décision" },
      { date: "18 déc. 2024", title: "Kader Attia — Repair", content: "Relire le travail d'Attia sur la réparation. La cicatrice ne doit pas être cachée, elle doit être nommée.", type: "découverte" },
    ],
    maintenant: { cherche: "La relation juste entre la pièce et le texte qui l'accompagne.", avancee: "Le principe de la soudure visible et de la réparation comme langage formel est défini.", bloque: null, prochaine: "Documenter les jonctions, les traces et leurs effets sur le corps qui porte la pièce.", question: "À quel moment une soudure devient-elle une cicatrice ?" },
    references: [
      { title: "Repair — 5 Acts", author: "Kader Attia", year: "2013" },
      { title: "Josèfa Ntjam — œuvre", author: "Josèfa Ntjam", year: "2015–" },
      { title: "Les Arts modestes", author: "Hervé Di Rosa et Bernard Belluc", year: "1980–" },
    ],
  },
  {
    id: "direction-artistique", wp_id: 0, title: "Bras de Fer", category: "graph.", status: "production",
    year: "2019–",
    question: "À quoi ressemble une image qui prend parti sans perdre sa beauté ?",
    manifeste: "L'affiche comme argument. La typographie comme corps. Chaque affiche est une prise de position.",
    description: "Direction artistique pour la scène musicale et culturelle. Identités visuelles, affiches, systèmes graphiques. Le graphisme comme acte politique — en filiation directe avec le situationnisme et la figuration narrative.",
    lastUpdated: "11 jan. 2025",
    themes: ["systèmes", "images"],
    tags: ["Graphisme", "Identité", "Affiche"],
    image: "https://images.unsplash.com/photo-1733232073397-80fb13ef3212?w=1400&h=900&fit=crop&auto=format",
    constellation: { x: 620, y: 180, r: 14 },
    fragmentCount: 11,
    journal: [
      { date: "11 jan. 2025", title: "Identité phase 2", content: "Le système graphique Bras de Fer entre dans sa deuxième phase. Moins de couleur, plus de corps dans la typographie.", type: "décision" },
    ],
    maintenant: { cherche: "Des formes qui résistent à la récupération commerciale — quelque chose qui ne peut pas être neutralisé.", avancee: "Le système graphique poursuit son déplacement vers une typographie plus physique et moins décorative.", bloque: null, prochaine: "Décliner le système entre affiches, édition et supports numériques.", question: "Quand est-ce qu'une image devient trop belle pour être honnête ?" },
    references: [
      { title: "La Société du spectacle", author: "Guy Debord", year: "1967" },
      { title: "Mythologies quotidiennes", author: "Gérald Gassiot-Talabot", year: "1964" },
      { title: "L'Art concret", author: "Theo van Doesburg", year: "1930" },
      { title: "Too Much World: Is the Internet Dead?", author: "Hito Steyerl", year: "2013" },
    ],
  },
];

export const FALLBACK_FRAGMENTS: Fragment[] = [
  {
    id: "f001", wp_id: 0, number: "F.001", title: "Le geste qui n'a pas de nom",
    date: "10 jan. 2025", type: "note",
    content: "En animant la main à trois doigts, j'ai produit un mouvement que je ne saurais pas décrire avec des mots. C'est peut-être ça, le point de départ.",
    status: "validé", keywords: ["geste", "langage", "corps"], projectIds: ["trois-doigts"],
    image: "https://images.unsplash.com/photo-1585571290034-3f59a2568563?w=800&h=600&fit=crop&auto=format",
  },
  {
    id: "f002", wp_id: 0, number: "F.002", title: "La fermeture comme position",
    date: "15 déc. 2024", type: "hypothèse",
    content: "La monade n'a pas de fenêtre — et c'est précisément pour ça qu'elle réfléchit tout. Être fermé n'est pas une limite. C'est une méthode.",
    status: "à relire", keywords: ["fermeture", "résonance", "système"], projectIds: ["la-monade"],
  },
  {
    id: "f003", wp_id: 0, number: "F.003", title: "La résine attend",
    date: "8 jan. 2025", type: "expérience",
    content: "Premier test résine + fibre optique + capteur de chaleur. Le bloc réagit à la présence humaine avant que l'œil ne le remarque. Il y a quelque chose d'inquiétant — et de juste.",
    status: "transformé", keywords: ["résine", "présence", "organisme"], projectIds: ["oeil-matiere"],
    image: "https://images.unsplash.com/photo-1588203379102-1a06c7d2ba1f?w=800&h=600&fit=crop&auto=format",
  },
  {
    id: "f004", wp_id: 0, number: "F.004", title: "La soudure reste",
    date: "3 jan. 2025", type: "note",
    content: "J'ai décidé de ne pas finir la surface. La trace de la soudure reste visible. Ce n'est pas un manque de soin — c'est la signature du travail.",
    status: "validé", keywords: ["soudure", "réparation", "trace"], projectIds: ["fragments-joaillerie"],
  },
  {
    id: "f005", wp_id: 0, number: "F.005", title: "Une image peut-elle mourir ?",
    date: "Nov. 2024", type: "question",
    content: "Steyerl parle d'image pauvre — dégradée par la circulation. Mais une image qui a trop circulé n'est pas morte. Elle est épuisée. Ce n'est pas la même chose.",
    status: "brut", keywords: ["image", "circulation", "dégradation"], projectIds: ["futur-animiste", "la-monade"],
  },
  {
    id: "f006", wp_id: 0, number: "F.006", title: "Le réalisme tue",
    date: "5 jan. 2025", type: "échec",
    content: "Test d'animation réaliste : la main ressemble à une main. Et alors ? Plus elle est précise, moins elle dit quelque chose. Le réalisme est une fausse piste.",
    status: "transformé", keywords: ["animation", "réalisme", "échec"], projectIds: ["trois-doigts"],
  },
  {
    id: "f007", wp_id: 0, number: "F.007", title: "Réparer, pas restaurer",
    date: "18 déc. 2024", type: "découverte",
    content: "Attia ne cache pas la blessure. Il la montre réparée — mais la réparation est visible, grossière parfois. C'est ça la différence entre réparer et restaurer. L'un nomme, l'autre efface.",
    status: "validé", keywords: ["réparation", "blessure", "Attia"], projectIds: ["fragments-joaillerie"],
  },
  {
    id: "f008", wp_id: 0, number: "F.008", title: "L'affiche comme corps",
    date: "Jan. 2025", type: "résultat",
    content: "Les meilleures affiches de cette série sont celles où la typographie a une densité physique. Pas une illustration — un poids. L'affiche pèse quelque chose.",
    status: "validé", keywords: ["affiche", "typographie", "poids"], projectIds: ["direction-artistique"],
  },
  {
    id: "f009", wp_id: 0, number: "F.009", title: "Sortir du loup",
    date: "Août 2026", type: "référence",
    content: "Chez Kiki Smith, le corps traverse l'animal, le conte et la matière. La métamorphose ne déguise pas le corps : elle lui rend plusieurs histoires possibles.",
    status: "à relire", keywords: ["Kiki Smith", "corps", "animal", "métamorphose"], projectIds: ["trois-doigts", "la-monade"],
  },
  {
    id: "f010", wp_id: 0, number: "F.010", title: "La couleur a une vitesse",
    date: "Août 2026", type: "hypothèse",
    content: "Une couleur ne remplit pas seulement une surface. Elle arrive, recule, vibre ou contamine la couleur voisine. Composer revient aussi à organiser ces vitesses.",
    status: "brut", keywords: ["couleur", "vitesse", "synesthésie", "perception"], projectIds: ["oeil-matiere", "la-monade"],
  },
  {
    id: "f011", wp_id: 0, number: "F.011", title: "Voir, c'est déjà classer",
    date: "Août 2026", type: "question",
    content: "Le regard reconnaît parce qu'il compare. Mais qui a construit les catégories avec lesquelles nous décidons qu'une image est vraie, belle, savante ou négligeable ?",
    status: "à relire", keywords: ["Gombrich", "Bourdieu", "regard", "classement"], projectIds: ["futur-animiste"],
  },
  {
    id: "f012", wp_id: 0, number: "F.012", title: "Le modeste n'est pas mineur",
    date: "Août 2026", type: "note",
    content: "L'objet modeste ne demande pas à entrer dans le grand art. Il oblige plutôt le grand art à expliquer pourquoi il l'avait laissé dehors.",
    status: "brut", keywords: ["art modeste", "objet", "culture populaire", "légitimation"], projectIds: ["fragments-joaillerie", "direction-artistique"],
  },
];

export const FALLBACK_SETTINGS: SiteSettings = {
  subtitle: "Artiste · Designer · Photographe · Autrice",
  city: "Basée à Paris",
  bio: "Mademo studio est une artiste, designer, photographe et autrice dont le travail traverse l'image, le corps, la matière, la politique et les formes sensibles du vivant.",
  bioSecondary: "Ce site fonctionne comme un atelier vivant, un carnet de recherche public et une archive artistique évolutive.",
  aboutImage: "",
  practices: ["Installation", "Animation", "Joaillerie", "Direction artistique", "Photographie", "Écriture & recherche"],
  available: ["Collaborations artistiques", "Résidences", "Commandes", "Direction artistique"],
  contact: {
    intro: "Pour collaborations, résidences, commandes ou simplement pour échanger.",
    email: "mademo@studio.fr",
    emailHref: "mailto:mademo@studio.fr",
    instagram: "@mademo.studio",
    instagramHref: "#",
    vimeo: "vimeo.com/mademo",
    vimeoHref: "#",
  },
};

export const FALLBACK_TEXTS: Text[] = [
  {
    id: "t1", wp_id: 0, title: "Ce que les mains savent", date: "Mars 2024", type: "Essai", readTime: "7 min",
    relatedProjectId: "trois-doigts",
    excerpt: "Le geste précède le langage. Toujours.",
    body: "Le geste précède le langage. Toujours. Avant de nommer ce que la main fait, la main l'a déjà fait — et parfois ce qu'elle fait n'a pas de nom. C'est dans cet écart que le film existe. Pas dans le récit, pas dans l'explication : dans ce que les doigts inventent quand on leur laisse le temps.",
  },
  {
    id: "t2", wp_id: 0, title: "La résine et le regard", date: "Nov. 2023", type: "Texte critique", readTime: "11 min",
    relatedProjectId: "oeil-matiere",
    excerpt: "Il y a un moment dans l'installation où l'on ne sait plus qui regarde quoi.",
    body: "Il y a un moment dans l'installation où l'on ne sait plus qui regarde quoi. La résine réagit à la présence — imperceptiblement d'abord, puis de manière évidente. Ce n'est pas un effet spécial. C'est un comportement. La distinction entre le vivant et l'inerte commence à vaciller.",
  },
  {
    id: "t3", wp_id: 0, title: "Réparer, pas restaurer", date: "Oct. 2023", type: "Essai", readTime: "9 min",
    relatedProjectId: "fragments-joaillerie",
    excerpt: "Restaurer, c'est effacer. Réparer, c'est nommer.",
    body: "Restaurer, c'est effacer. Réparer, c'est nommer. La différence est politique. Quand je laisse la soudure visible, je ne montre pas mon manque de soin — je montre que quelque chose a été cassé, et que ça compte. La trace du travail est le vrai sujet de la pièce.",
  },
  {
    id: "t4", wp_id: 0, title: "Notes sur Bras de Fer", date: "Jan. 2025", type: "Journal", readTime: "5 min",
    relatedProjectId: "direction-artistique",
    excerpt: "L'affiche est un argument. Pas une décoration.",
    body: "L'affiche est un argument. Pas une décoration. Quand on travaille pour la scène musicale, il y a une tentation de faire beau — de séduire. Mais séduire et convaincre ne sont pas la même chose. Bras de Fer, depuis le début, cherche autre chose : une image qui prend position. Qui a un corps.",
  },
  {
    id: "t5", wp_id: 0, title: "La monade comme programme", date: "Jan. 2024", type: "Recherche", readTime: "18 min",
    relatedProjectId: "la-monade",
    excerpt: "Leibniz disait que la monade n'a pas de fenêtre. J'y vois une méthode.",
    body: "Leibniz disait que la monade n'a pas de fenêtre. J'y vois une méthode : une forme autonome qui ne reçoit pas passivement le monde, mais le réfracte depuis sa propre position. La Monade ne désigne donc pas l'isolement. Elle organise une tension entre fermeture, mémoire et relation. Chaque projet, texte ou fragment y conserve son autonomie tout en faisant apparaître des connexions invisibles avec les autres.",
  },
  {
    id: "t6", wp_id: 0, title: "L'imaginaire comme contre-pouvoir", date: "Août 2026", type: "Recherche", readTime: "8 min",
    relatedProjectId: "trois-doigts",
    excerpt: "Le rêve n'est pas le contraire du politique.",
    body: "Le rêve n'est pas le contraire du politique. L'absurde, le grotesque et la métamorphose déplacent les récits que le pouvoir présente comme naturels. Un corps impossible, un objet détourné ou une image mal assemblée ouvrent une brèche : ils montrent que le réel aurait pu être construit autrement. Le surréalisme politique commence dans cette fissure.",
  },
  {
    id: "t7", wp_id: 0, title: "La vitesse des couleurs", date: "Août 2026", type: "Note de recherche", readTime: "6 min",
    relatedProjectId: "oeil-matiere",
    excerpt: "Une couleur n'occupe jamais seulement une surface : elle produit une durée.",
    body: "Une couleur n'occupe jamais seulement une surface : elle produit une durée. Certaines teintes avancent, d'autres semblent se retirer ; certaines vibrent au contact de leur voisine. Dans l'image animée, l'installation ou l'interface, la couleur devient un événement. La composition ne consiste plus seulement à associer des tons, mais à organiser leurs vitesses d'apparition, de déplacement et de disparition.",
  },
];
